// Generated by gencpp from file learning_communication/AddInts.msg
// DO NOT EDIT!


#ifndef LEARNING_COMMUNICATION_MESSAGE_ADDINTS_H
#define LEARNING_COMMUNICATION_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <learning_communication/AddIntsRequest.h>
#include <learning_communication/AddIntsResponse.h>


namespace learning_communication
{

struct AddInts
{

typedef AddIntsRequest Request;
typedef AddIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInts
} // namespace learning_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learning_communication::AddInts > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::learning_communication::AddInts&) { return value(); }
};

template<>
struct DataType< ::learning_communication::AddInts > {
  static const char* value()
  {
    return "learning_communication/AddInts";
  }

  static const char* value(const ::learning_communication::AddInts&) { return value(); }
};


// service_traits::MD5Sum< ::learning_communication::AddIntsRequest> should match
// service_traits::MD5Sum< ::learning_communication::AddInts >
template<>
struct MD5Sum< ::learning_communication::AddIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learning_communication::AddInts >::value();
  }
  static const char* value(const ::learning_communication::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_communication::AddIntsRequest> should match
// service_traits::DataType< ::learning_communication::AddInts >
template<>
struct DataType< ::learning_communication::AddIntsRequest>
{
  static const char* value()
  {
    return DataType< ::learning_communication::AddInts >::value();
  }
  static const char* value(const ::learning_communication::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learning_communication::AddIntsResponse> should match
// service_traits::MD5Sum< ::learning_communication::AddInts >
template<>
struct MD5Sum< ::learning_communication::AddIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learning_communication::AddInts >::value();
  }
  static const char* value(const ::learning_communication::AddIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_communication::AddIntsResponse> should match
// service_traits::DataType< ::learning_communication::AddInts >
template<>
struct DataType< ::learning_communication::AddIntsResponse>
{
  static const char* value()
  {
    return DataType< ::learning_communication::AddInts >::value();
  }
  static const char* value(const ::learning_communication::AddIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARNING_COMMUNICATION_MESSAGE_ADDINTS_H
