<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot_name">
	<xacro:property name="PI" value="3.14159"/>
	<xacro:property name="radius" value="0.03"/>
	<!-- 属性调用 -->
	<myxacro_property name="${radius}"/>
	<!-- 算术运算 -->
	<myxacro_property result="${radius*2}"/>

	<!-- 宏定义 -->
	<xacro:macro name="getSum" params="num1 num2">
		<result value="${num1+num2}"/>
	</xacro:macro>
	<!-- 宏调用 -->
	<xacro:getSum num1="1" num2="2"/>

	<!-- 文件包含 -->
	<xacro:include filename="$(find learning_urdf_rviz_gazebo)/urdf/xacro/demo01_helloworld.xacro"/>
	
</robot>